# Generated by Django 2.2.4 on 2020-04-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_hackathontribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathontribe',
            name='hackathon',
        ),
        migrations.AddField(
            model_name='hackathontribe',
            name='hackathons',
            field=models.ManyToManyField(help_text='Add hackathons this tribe sponsors.', to='dashboard.HackathonEvent'),
        ),
        migrations.AddField(
            model_name='hackathontribe',
            name='tribe_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hackathontribe',
            name='profile',
            field=models.ForeignKey(help_text='Tribe profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Profile'),
        ),
    ]
