# Generated by Django 2.2.4 on 2020-04-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0101_auto_20200407_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathontribe',
            name='visible',
            field=models.BooleanField(default=True, help_text='Can this HackathonTribe be seen on /hackathons ?'),
        ),
    ]
