# Generated by Django 2.2.4 on 2020-04-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0102_hackathontribe_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathontribe',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='hackathontribe',
            name='tribe_name',
        ),
    ]
