# Generated by Django 2.2.4 on 2020-04-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0103_auto_20200407_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathontribe',
            name='visible',
            field=models.BooleanField(default=True, help_text='Can this HackathonTribe be seen on /hackathons? Override if shown already.'),
        ),
    ]
